grafana:
  enabled: true
  service:
    type: ClusterIP
  adminPassword: ${grafana_admin_password}

  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      labelValue: "1"
      searchNamespace: ALL
      folderAnnotation: grafana_folder
      provider:
        foldersFromFilesStructure: true

  assertNoLeakedSecrets: false

  persistence:
    enabled: false

  additionalDataSources:
    - name: Loki
      type: loki
      access: proxy
      url: http://loki.observability.svc.cluster.local:3100
      jsonData:
        derivedFields:
          - datasourceUid: tempo
            matcherRegex: '"trace_id":"(\w+)"'
            name: TraceID
            url: $${__value.raw}
    - name: Tempo
      type: tempo
      uid: tempo
      access: proxy
      url: http://tempo.observability.svc.cluster.local:3100
      jsonData:
        tracesToLogs:
          datasourceUid: loki
          tags: ['service.name', 'k8s.pod.name']
          mappedTags:
            - key: service.name
              value: service

prometheus:
  prometheusSpec:
    storageSpec: {}
    enableFeatures:
      - exemplar-storage
    enableRemoteWriteReceiver: true
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false

alertmanager:
  enabled: true

nodeExporter:
  enabled: true

kubeStateMetrics:
  enabled: true
